### ISSUE TITLE
My car key shows up as smoke detector / Win7 .NET errors

### ISSUE THREAD

**Issue by Phaerox** [marco402/plugin-Rtl433-for-SdrSharp#8]
Hey, great plugin.
I have set up a big discone antenna in my backyard and still learn about SDR possibilities. Please forgive me if i can't go into super technical stuff yet. But what I already discovered when playing around with the plugin and what might interest you: When it's running and I press my car keys, it shows up as Protocol:86 Model: Smoke-GS558. I verified it. Pressing the key multiple times increases the "No. of messages" accordingly to the key presses. If I hold the key down, I see the long signal in the spectrum. Car is a 2008 Opel Astra H (Could be Vauxhall in other countries, I'm in Germany).

Also another problem I have is the fact that it throws a .NET error when starting up the plugin. It might be a problem on my side because for the SDR stuff I am using an outdated Windows 7 Laptop that probably doesn't get the latest and greatest .NET updates anymore. However, maybe someone can throw me a hint here. I also have a way to move around the problem:
When starting the Plugin, it throws a .NET error. If I click "continue", then stop the plugin, and start it again, it works for a while.
When I use the plugin for a few weeks, and the devices.txt fills up (I always load and save), sometimes a point is reached where it completely breaks. If that happens, the NET error keeps spamming, even if i click "continue". To fix this, I have to rename/delete the devices.txt and start fresh. Then it will work again for a while. This is the one time error it shows at every start:

************** Ausnahmetext **************
System.IO.IOException: Das Handle ist ungültig.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.GetFileOptions()
   at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access, Int32 bufferSize)
   at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access)
   at SDRSharp.Rtl_433.Rtl_433_Processor.openConsole()
   at SDRSharp.Rtl_433.Rtl_433_Panel.Start(Boolean senderRadio)
   at SDRSharp.Rtl_433.Rtl_433_Panel.buttonStartStop_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by marco402** [comment]
Hello phaerox

For the device.txt problem, is there enough free byte left on the disk?

For crashing you can try:
to fix you must simply download and install Microsoft Visual C++ 2013 Redistributable x86/x64.

https://forums.radioreference.com/threads/rtl433-plugin-for-sdr-now-available.425703/page-10:

Marc

**Comment by Phaerox** [comment]
Hey thanks for the reply. Yes, there is enough space left. It's a 256GB SSD with 20GB free.
I tried installing Visual C++ 2013 Redistributable and it didn't fix the crash, however I noticed the installation took INSANELY long, like 45 Minutes. It finished wothout an error but the time it took seems suspect. I will probably try to wipe the whole laptop and reinstall everything fresh.
